#!/usr/bin/env bash
# gen-config.sh: generate harness/config.yaml plus one bearer token file
# per agent under harness/tokens/.
#
# Re-runnable: existing token files are reused (so tokens already handed
# to scenario agents keep working) and only missing ones are minted.
# Pass --rotate to mint fresh tokens for every agent.
#
# Token shape matches internal/identity: the config stores only
# token_sha256 = lowercase SHA-256 hex of the exact plaintext bytes.
# Token files carry no trailing newline.

set -euo pipefail

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$HARNESS_DIR/.." && pwd)"
TOKENS_DIR="$HARNESS_DIR/tokens"
RUN_DIR="$HARNESS_DIR/run"
CONFIG="$HARNESS_DIR/config.yaml"
CATALOG_PATH="$REPO_DIR/examples/catalog/"
DATASET_PATH="$REPO_DIR/testdata/iam-dataset.json"
ROTATE=0

for arg in "$@"; do
  case "$arg" in
    --rotate) ROTATE=1 ;;
    *) echo "gen-config.sh: unknown flag $arg" >&2; exit 2 ;;
  esac
done

mkdir -p "$TOKENS_DIR" "$RUN_DIR"
chmod 700 "$TOKENS_DIR"

# sha256_hex prints the lowercase SHA-256 hex of its argument's exact
# bytes (no trailing newline added).
sha256_hex() { printf '%s' "$1" | shasum -a 256 | cut -d' ' -f1; }

# ensure_token prints the SHA-256 hex for one agent, minting the token
# file when it is missing.
ensure_token() {
  local agent="$1" file="$TOKENS_DIR/$agent.token" tok
  if [ "$ROTATE" -eq 1 ] || [ ! -s "$file" ]; then
    tok="tgt_$(openssl rand -hex 32)"
    printf '%s' "$tok" > "$file"
    chmod 600 "$file"
  else
    tok="$(cat "$file")"
  fi
  sha256_hex "$tok"
}

AGENT_IDS=()
for n in $(seq -w 1 100); do AGENT_IDS+=("agent-$n"); done
AGENT_IDS+=("agent-201" "agent-expired")

{
  cat <<YAML
# taskgrant scenario-fleet broker config. GENERATED by harness/gen-config.sh.
# Do not hand-edit: regenerate instead. Scenario agents treat this file as
# read-only.
version: 1

server:
  transport: http
  listen: 127.0.0.1:8770
  admin_socket: $RUN_DIR/admin.sock
  max_wait_seconds: 60
  credential_redelivery: false

aws:
  sts_region: us-east-1
  endpoint_url: http://localhost:4566
  default_duration_seconds: 900
  max_duration_seconds: 3600
  accounts:
    - "000000000000"

synth:
  catalog_path: $CATALOG_PATH
  dataset_path: $DATASET_PATH

guardrails:
  access_levels: [Read, List, Write]
  first_use_approval: false

approvals:
  pending_ttl_seconds: 180
  rules:
    # Everything minted under the approval-gated profile parks for a human
    # (scenarios S065-S071). Capabilities whose catalog entry sets
    # requires_approval: true (s3.write-prefix, lambda.invoke) park on every
    # profile, which is what S072 exercises.
    - match:
        profile: approval-gated
      action: require_approval

revocation:
  enabled: true
  revoke_on_release: false

log:
  path: $RUN_DIR/decisions.db
  mirror_jsonl: $RUN_DIR/decisions.jsonl
  retention_days: 0

profiles:
  default:
    role_arn: arn:aws:iam::000000000000:role/taskgrant-default
    max_duration_seconds: 1800
    region: us-east-1
  approval-gated:
    role_arn: arn:aws:iam::000000000000:role/taskgrant-approval-gated
    max_duration_seconds: 1800
    region: us-east-1
  short-cap:
    role_arn: arn:aws:iam::000000000000:role/taskgrant-short-cap
    max_duration_seconds: 900
    region: us-east-1
  narrow:
    role_arn: arn:aws:iam::000000000000:role/taskgrant-narrow
    max_duration_seconds: 1800
    region: us-east-1

agents:
YAML

  for agent in "${AGENT_IDS[@]}"; do
    hash="$(ensure_token "$agent")"
    case "$agent" in
      agent-expired)
        expires="2020-01-01T00:00:00Z"
        profiles="[default]"
        default_profile="default"
        ;;
      agent-201)
        expires="2027-01-01T00:00:00Z"
        profiles="[default]"
        default_profile="default"
        ;;
      agent-077)
        # Narrow-visibility probe (S077): profile allowlist of one.
        expires="2027-01-01T00:00:00Z"
        profiles="[narrow]"
        default_profile="narrow"
        ;;
      *)
        expires="2027-01-01T00:00:00Z"
        profiles="[default, approval-gated, short-cap, narrow]"
        default_profile="default"
        ;;
    esac
    cat <<YAML
  $agent:
    token_sha256: "$hash"
    token_expires: $expires
    profiles: $profiles
    default_profile: $default_profile
YAML
  done
} > "$CONFIG.tmp"

mv "$CONFIG.tmp" "$CONFIG"
chmod 644 "$CONFIG"

echo "gen-config.sh: wrote $CONFIG"
echo "gen-config.sh: ${#AGENT_IDS[@]} agents, tokens in $TOKENS_DIR (mode 0600)"
